apiVersion: reconcilers.nebari.dev/v1
kind: NebariApp
metadata:
  name: my-pack
spec:
  # REQUIRED: Replace with your Nebari cluster hostname
  hostname: my-pack.nebari.example.com

  service:
    name: my-pack
    port: 80

  routing:
    routes:
      - pathPrefix: /
        pathType: PathPrefix
    tls:
      enabled: true

  auth:
    enabled: false
    provider: keycloak
    provisionClient: true
    redirectURI: /
    scopes:
      - openid
      - profile
      - email

  gateway: public
